pipeline:
    docker:
        image: plugins/docker
        repo: sh4d1/resume
        tags: ${DRONE_COMMIT_SHA:0:8}
        username: sh4d1
        secrets: [ docker_password ] 
    deploy:
        image: quay.io/honestbee/drone-kubernetes
#        kubernetes_server: ${KUBERNETES_SERVER}
#        kubernetes_cert: ${KUBERNETES_CERT}
#        kubernetes_token: ${KUBERNETES_TOKEN}
        deployment: resume
        container: resume
        secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
