pipeline:
    docker:
        image: plugins/docker
        repo: sh4d1/resume
        tags: ${DRONE_COMMIT_SHA:0:8}
        username: sh4d1
        secrets: [ docker_password ] 
    deploy:
        image: quay.io/honestbee/drone-kubernetes
        kubernetes_server: ${KUBERNETES_SERVER}
        kubernetes_cert: ${KUBERNETES_CERT}
        kubernetes_token: ${KUBERNETES_TOKEN}
        deployment: resume
        repo: sh4d1/resume
        container: resume
        tag:
            - ${DRONE_COMMIT_SHA:0:8}
        secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
